services:
  - type: web
    name: resume-matcher
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_APP
        value: app/main.py
      - key: FLASK_ENV
        value: production
      - key: GROQ_API_KEY
        sync: false
    buildCommand: pip install -r requirements.txt && python -m spacy download en_core_web_sm
    startCommand: flask run --host 0.0.0.0
    healthCheckPath: /
    autoDeploy: true